-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 21:04:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema NOTICES_CREATION_DB
-- -----------------------------------------------------
-- Database For Notices Creation Project.

-- -----------------------------------------------------
-- Schema NOTICES_CREATION_DB
--
-- Database For Notices Creation Project.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NOTICES_CREATION_DB` DEFAULT CHARACTER SET utf8 ;
USE `NOTICES_CREATION_DB` ;

-- -----------------------------------------------------
-- Table `NOTICES_CREATION_DB`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NOTICES_CREATION_DB`.`USER` ;

CREATE TABLE IF NOT EXISTS `NOTICES_CREATION_DB`.`USER` (
  `ID` DECIMAL NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `REGISTRATION_DATE` DATETIME NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NOTICES_CREATION_DB`.`NOTICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NOTICES_CREATION_DB`.`NOTICE` ;

CREATE TABLE IF NOT EXISTS `NOTICES_CREATION_DB`.`NOTICE` (
  `ID` DECIMAL NOT NULL,
  `NOTICE` VARCHAR(45) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `UPDATE_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `NOTICE_UNIQUE` (`NOTICE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NOTICES_CREATION_DB`.`USER_HAS_NOTICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NOTICES_CREATION_DB`.`USER_HAS_NOTICE` ;

CREATE TABLE IF NOT EXISTS `NOTICES_CREATION_DB`.`USER_HAS_NOTICE` (
  `USER_ID` DECIMAL NOT NULL,
  `NOTICE_ID` DECIMAL NOT NULL,
  PRIMARY KEY (`USER_ID`, `NOTICE_ID`),
  INDEX `fk_USER_has_NOTICE_NOTICE1_idx` (`NOTICE_ID` ASC),
  INDEX `fk_USER_has_NOTICE_USER_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_USER_has_NOTICE_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `NOTICES_CREATION_DB`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_NOTICE_NOTICE1`
    FOREIGN KEY (`NOTICE_ID`)
    REFERENCES `NOTICES_CREATION_DB`.`NOTICE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
